# Global build settings (these will be default for all contexts unless overridden)
[build]
  command = "npm run build"  # Your build command
  publish = "build/"         # Directory (relative to base) to publish
  base    = ""               # Base directory (root of repo)

# Production context: Deploys from gh-pages branch
[context.production]
  command = "echo 'Deploying pre-built gh-pages branch. No build needed.'" # Override build command
  publish = "/" # Publish the entire root of the gh-pages branch

# Deploy Preview context: For PRs (typically against master)
[context.deploy-preview]
  # This context will inherit the global [build] settings above, which are:
  # command = "npm run build"
  # publish = "build/"
  # base    = ""
  # These are correct for building PRs from your source code in master.
