# Global build settings
[build]
  command = "npm run build"
  publish = "build/"
  base    = ""

[build.environment]
  PUBLIC_URL = "/"

# Production context: Deploys from gh-pages branch
[context.production]
  command = "echo 'Deploying pre-built gh-pages branch. No build needed.'"
  publish = "/"

# Deploy Preview context: For PRs
[context.deploy-preview]
  # Inherits global [build] and [build.environment] settings
